// icons.js — auto-generated by build_icons.js
// Each value is a <svg><use> string.
// Requires sprite.svg to be present in the DOM before these render.
//
// Usage (identical to your current code):
//   label: `
//     <span class="icon-label">
//       ${ICONS["information"]}
//       Hallway
//     </span>
//   `

const ICONS = {
  "air-transportation": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-air-transportation"></use></svg>`,
  "arrivingflights": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-arrivingflights"></use></svg>`,
  "baggagecheckin": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-baggagecheckin"></use></svg>`,
  "baggageclaim": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-baggageclaim"></use></svg>`,
  "baggagelockers": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-baggagelockers"></use></svg>`,
  "bar": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-bar"></use></svg>`,
  "barbershop-beautysalon": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-barbershop-beautysalon"></use></svg>`,
  "barbershop": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-barbershop"></use></svg>`,
  "beautysalon": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-beautysalon"></use></svg>`,
  "bus": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-bus"></use></svg>`,
  "car-rental": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-car-rental"></use></svg>`,
  "cashier": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-cashier"></use></svg>`,
  "coatcheck": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-coatcheck"></use></svg>`,
  "coffee-shop": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-coffee-shop"></use></svg>`,
  "currencyexchange": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-currencyexchange"></use></svg>`,
  "departingflights": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-departingflights"></use></svg>`,
  "down-arrow": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-down-arrow"></use></svg>`,
  "drinkingfountain": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-drinkingfountain"></use></svg>`,
  "elevator": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-elevator"></use></svg>`,
  "escalator-down": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-escalator-down"></use></svg>`,
  "escalator-up": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-escalator-up"></use></svg>`,
  "escalator": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-escalator"></use></svg>`,
  "exit": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-exit"></use></svg>`,
  "fireextinguisher": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-fireextinguisher"></use></svg>`,
  "firstaid": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-firstaid"></use></svg>`,
  "forward-and-left-arrow": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-forward-and-left-arrow"></use></svg>`,
  "forward-and-right-arrow": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-forward-and-right-arrow"></use></svg>`,
  "forward-andright-arrow": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-forward-andright-arrow"></use></svg>`,
  "ground-transportation": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-ground-transportation"></use></svg>`,
  "heliport": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-heliport"></use></svg>`,
  "hotel-information": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-hotel-information"></use></svg>`,
  "information": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-information"></use></svg>`,
  "left-and-down-arrow": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-left-and-down-arrow"></use></svg>`,
  "leftarrow": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-leftarrow"></use></svg>`,
  "litter-disposal": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-litter-disposal"></use></svg>`,
  "lostandfound": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-lostandfound"></use></svg>`,
  "mail": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-mail"></use></svg>`,
  "no-entry": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-no-entry"></use></svg>`,
  "no-smoking": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-no-smoking"></use></svg>`,
  "nodogs": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-nodogs"></use></svg>`,
  "noparking": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-noparking"></use></svg>`,
  "nursery": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-nursery"></use></svg>`,
  "parking": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-parking"></use></svg>`,
  "rail-transportation": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-rail-transportation"></use></svg>`,
  "restaurant": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-restaurant"></use></svg>`,
  "right-and-down-arrow": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-right-and-down-arrow"></use></svg>`,
  "right-arrow": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-right-arrow"></use></svg>`,
  "shops": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-shops"></use></svg>`,
  "smoking": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-smoking"></use></svg>`,
  "stairs-down": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-stairs-down"></use></svg>`,
  "stairs-up": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-stairs-up"></use></svg>`,
  "stairs": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-stairs"></use></svg>`,
  "taxi": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-taxi"></use></svg>`,
  "telephone": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-telephone"></use></svg>`,
  "ticketpurchase": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-ticketpurchase"></use></svg>`,
  "toilets-men": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-toilets-men"></use></svg>`,
  "toilets-women": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-toilets-women"></use></svg>`,
  "toilets": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-toilets"></use></svg>`,
  "uparrow": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-uparrow"></use></svg>`,
  "waitingroom": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-waitingroom"></use></svg>`,
  "water-transportation": `<svg class="aiga-icon" aria-hidden="true" focusable="false"><use href="#icon-water-transportation"></use></svg>`
};
