"""
builders/_shared.py — helpers shared by every page-type builder.

Split out of the original generate_html.py so a new page type only needs a
new sibling module registered in builders/__init__.py, not edits scattered
through one growing file.
"""

import json


def build_layers_js(buttons: list[dict]) -> str:
    """Render the PAGE_CONFIG layers array body from a list of button dicts."""
    entries = []
    for b in buttons:
        lnum    = b["layer"]
        icon    = b.get("icon", "information")
        label   = b.get("label", f"layer {lnum}")
        href    = b.get("href")
        message = b.get("message")
        transit = b.get("transit", [])

        if href == "back":
            nav_href = "javascript:history.back()"
        elif href:
            nav_href = f"{href}.html"
        else:
            nav_href = "#"

        transit_paths = [f"images/transit/{t}" for t in transit]
        if not transit_paths:
            transit_js = '""'
        elif len(transit_paths) == 1:
            transit_js = f'"{transit_paths[0]}"'
        else:
            items = ", ".join(f'"{t}"' for t in transit_paths)
            transit_js = f"[{items}]"

        # label is interpolated into a JS template literal below (the
        # backtick string around <span class="icon-label">...). Escaping
        # only backticks isn't enough — a label containing "${...}" would
        # be evaluated as a live JS expression at page-load. Escape both.
        label_esc    = label.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
        message_js   = json.dumps(message) if message else "null"
        vn_only_line = "\n            vnOnly: true," if message else ""

        entries.append(
            f'          {{\n'
            f'            id: "layer-{lnum:02d}",\n'
            f'            href: "{nav_href}",{vn_only_line}\n'
            f'            message: {message_js},\n'
            f'            transitImage: {transit_js},\n'
            f'            label: `\n'
            f'        <span class="icon-label">\n'
            f'          ${{ICONS["{icon}"]}}\n'
            f'          {label_esc}\n'
            f'        </span>\n'
            f'      `,\n'
            f'          }},'
        )
    return "\n".join(entries)


def build_imgs_html(page_id: str, buttons: list[dict]) -> str:
    """Render the <img> tag block for the scene div."""
    tags = [
        f'        <img class="layer" id="layer-00"\n'
        f'             src="images/{page_id}-0.png" alt="" draggable="false" />'
    ]
    for b in buttons:
        lnum = b["layer"]
        tags.append(
            f'        <img class="layer" id="layer-{lnum:02d}"\n'
            f'             src="images/{page_id}-{lnum}.png" alt="" draggable="false" />'
        )
    return "\n".join(tags)


def build_head(page: dict, extra_style: str = "") -> str:
    """Render the shared <head> block. extra_style is injected after style.css."""
    page_id   = page["id"]
    title     = page.get("title", f"Airport — {page_id}")
    buttons   = page.get("buttons", [])
    layers_js = build_layers_js(buttons)
    pulse_js  = "true" if page.get("pulse") else "false"

    slideshow_cfg = page.get("slideshow")
    if slideshow_cfg:
        imgs_js   = json.dumps([f"images/slideshow/{i}" for i in slideshow_cfg["images"]])
        ss_block  = f"""
        slideshow: {{
          images:       {imgs_js},
          interval:     {int(slideshow_cfg.get("interval", 4000))},
          fadeDuration: {int(slideshow_cfg.get("fadeDuration", 1200))},
          loop:         {"true" if slideshow_cfg.get("loop", True) else "false"},
          drift:        {"true" if slideshow_cfg.get("drift", False) else "false"},
        }},"""
    else:
        ss_block = ""

    return f"""  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <title>{title}</title>

    <link rel="icon" type="image/png" href="images/airport.png" />
    <meta property="og:title"       content="{title}" />
    <meta property="og:description" content="A point and click adventure. Recreating airport hell." />
    <meta property="og:image"       content="https://kyrielie.github.io/webvoyage/images/{page_id}-0.png" />
    <meta property="og:type"        content="website" />
    <meta name="twitter:card"       content="summary_large_image" />

    <style>
      html, body {{ background: #000; margin: 0; }}
    </style>

    <link rel="stylesheet" href="style.css" />
{extra_style}
    <!-- ═══════════════════════════════════════════════════════════════
         PAGE CONFIG — generated by generate_html.py from pages.json
         Do not edit by hand. Edit pages.json and re-run the script.
    ════════════════════════════════════════════════════════════════ -->
    <!-- icons.js must be a plain script (no `export`) so ICONS is a global -->
    <script src="icons.js"></script>
    <script>
      window.PAGE_CONFIG = {{
        name: "{page_id}",
        message: {json.dumps(page.get("message") or "")},
        pulse: {pulse_js},{ss_block}
        layers: [
{layers_js}
        ],
      }};
    </script>
  </head>"""


def build_body_common_top() -> str:
    """Shared body elements that appear on every page type."""
    return """\
    <!-- AIGA icon sprite — fetched once, injected so <use href="#icon-…"> works -->
    <script>
      fetch('sprite.svg')
        .then(r => r.text())
        .then(svg => {
          const div = document.createElement('div');
          div.style.display = 'none';
          div.setAttribute('aria-hidden', 'true');
          div.innerHTML = svg;
          document.body.insertBefore(div, document.body.firstChild);
        });
    </script>

    <div class="scanlines" aria-hidden="true"></div>
    <div class="vignette"  aria-hidden="true"></div>
    <div id="tooltip" class="tooltip" role="tooltip"></div>"""


def build_transit_template() -> str:
    """The <template id="transit-tpl"> block cloned by main.js on navigation.
    Identical on every page type — factored out so it can't drift between
    the standard and slideshow builders the way two independent copies
    eventually would."""
    return """\
    <!-- Transit overlay template — cloned by main.js on navigation. -->
    <template id="transit-tpl">
      <div id="transit-overlay">
        <div id="transit-frame">
          <img id="transit-photo" src="" alt="" />
          <canvas id="transit-noise"></canvas>
          <div id="transit-tracking-band"></div>
        </div>
        <div id="transit-hud-bottom">
          <div id="transit-label">LOADING<span id="transit-ellipsis"></span></div>
          <div id="transit-bar-wrap">
            <div id="transit-bar-segments"></div>
            <div id="transit-bar"></div>
          </div>
          <div id="transit-pct">0%</div>
        </div>
      </div>
    </template>"""
