"""
builders/slideshow.py — a full-viewport crossfading image sequence behind
the standard scene layer stack.

Extra DOM injected vs standard:
  • #slideshow-wrap + #slide-a + #slide-b  — two-buffer crossfade
  • <style> block scoped to slideshow layout
  • Inline <script> slideshow engine (reads PAGE_CONFIG.slideshow)

main.js is still loaded unchanged — it handles the window-frame layer
hit-testing and the "land" button navigation exactly as on any other page.
The slideshow script only touches #slide-a and #slide-b.
"""

from . import _shared

_SLIDESHOW_STYLE = """
    <style>
      /* ── Slideshow layout ─────────────────────────────────────────
         #slideshow-wrap sits below #scene in the stacking context.
         The window-frame cutout PNG lets the slides show through.
      ──────────────────────────────────────────────────────────── */
      #slideshow-wrap {
        position: fixed;
        inset: 0;
        z-index: 0;
        overflow: hidden;
        background: #000;
      }
      .slide {
        position: absolute;
        inset: 0;
        width: 100%;
        height: 100%;
        object-fit: cover;
        opacity: 0;
        /* --fade-ms is set from PAGE_CONFIG.slideshow.fadeDuration by the inline script */
        transition: opacity var(--slide-fade-ms, 1200ms) ease;
        image-rendering: pixelated;
        pointer-events: none;
        user-select: none;
      }
      .slide.active { opacity: 1; }
      /* Ensure the scene (window frame + hit layers) sits above the slides */
      .scene-wrap { position: relative; z-index: 1; }
    </style>
"""


def build(page: dict) -> str:
    page_id = page["id"]
    buttons = page.get("buttons", [])

    head        = _shared.build_head(page, extra_style=_SLIDESHOW_STYLE)
    imgs_html   = _shared.build_imgs_html(page_id, buttons)
    body_top    = _shared.build_body_common_top()
    transit_tpl = _shared.build_transit_template()

    slideshow_script = """\
    <!-- Slideshow engine — generated by generate_html.py. Do not edit by hand. -->
    <script>
      (function () {
        var cfg  = window.PAGE_CONFIG.slideshow;
        var imgs = cfg.images;
        var slA  = document.getElementById('slide-a');
        var slB  = document.getElementById('slide-b');

        // Expose fade duration to CSS
        document.documentElement.style.setProperty(
          '--slide-fade-ms', cfg.fadeDuration + 'ms'
        );

        var idx    = 0;
        var active = slA;
        var next   = slB;

        function loadSlide(el, src) {
          el.src = src;
        }

        function advance() {
          var nextIdx = (idx + 1) % imgs.length;
          if (!cfg.loop && nextIdx === 0) return;
          idx = nextIdx;

          // Preload into the inactive buffer, swap on load
          next.classList.remove('active');
          next.onload = function () {
            active.classList.remove('active');
            next.classList.add('active');
            var tmp = active;
            active  = next;
            next    = tmp;
            // Preload the slide after next while current is visible
            var preloadIdx = (idx + 1) % imgs.length;
            if (cfg.loop || preloadIdx !== 0) {
              next.src = imgs[preloadIdx];
            }
          };
          next.src = imgs[idx];
        }

        // Load and show first slide immediately
        slA.onload = function () { slA.classList.add('active'); };
        loadSlide(slA, imgs[0]);

        // Preload second slide into buffer
        if (imgs.length > 1) { slB.src = imgs[1]; }

        setInterval(advance, cfg.interval);

        // Optional slow horizontal drift — images should be ~120% scene width
        if (cfg.drift) {
          var wrap = document.getElementById('slideshow-wrap');
          wrap.style.width = '120%';
          wrap.style.left  = '-10%';
          var driftLeft = true;
          function driftStep() {
            wrap.style.transition = 'left 25000ms linear';
            wrap.style.left = driftLeft ? '0%' : '-10%';
            driftLeft = !driftLeft;
          }
          driftStep();
          setInterval(driftStep, 25000);
        }
      })();
    </script>"""

    return f'''<!doctype html>
<html lang="en" style="background:#000">
{head}
  <body>
{body_top}

    <!-- Slideshow layer — sits below #scene, shows through the window-frame cutout -->
    <div id="slideshow-wrap" aria-hidden="true">
      <img id="slide-a" class="slide" src="" alt="" />
      <img id="slide-b" class="slide" src="" alt="" />
    </div>

    <main class="scene-wrap">
      <div class="scene" id="scene">
{imgs_html}
      </div>
    </main>

{transit_tpl}

    <script type="module" src="main.js"></script>
{slideshow_script}
  </body>
</html>
'''
